Repository opensource-nepal/py-nepali, pull requests merged in 2023-02, with the labels that each got.

#18 Minor refactoring
  CHANGELOG.md
  nepali/datetime/_converter.py
  nepali/tests/test_datetime.py
Labels: refactor

#20 unittest updated for phone_numbers and locations
  Makefile
  nepali/locations/models.py
  nepali/tests/test_date_converter.py
  nepali/tests/test_locations.py
  nepali/tests/test_phone_number.py
Labels: refactor, unittest

#21 Unittest added for nepali number and timezone
  CHANGELOG.md
  nepali/number.py
  nepali/tests/test_number.py
  nepali/tests/test_timezone.py
  nepali/timezone.py
Labels: refactor, unittest

#22 Update setup.py
  setup.py
Labels: minor changes

#23 Refactored date converter code with reusability
  nepali/date_converter.py
  nepali/tests/test_date_converter.py
Labels: refactor, unittest

#24 Strftime and Humanize datetime refactored, unittest added
  CHANGELOG.md
  nepali/datetime/_datetime.py
  nepali/datetime/_formatter.py
  nepali/datetime/_humanize.py
  nepali/tests/test_datetime.py
  nepali/tests/test_humanize.py
Labels: refactor, unittest, improvement

#25 Add pre-commit hook
  .editorconfig
  .gitignore
  .pre-commit-config.yaml
  requirements.txt
Labels: enhancement, good first issue

#26 comment updated
  .editorconfig
Labels: refactor

#27 Code reformatted using 'black .'
  .github/workflows/python-package.yml
  nepali/__init__.py
  nepali/char.py
  nepali/date_converter.py
  nepali/datetime/__init__.py
  nepali/datetime/_datetime.py
  nepali/datetime/_formatter.py
  nepali/datetime/_humanize.py
  nepali/datetime/parser/__init__.py
  nepali/datetime/parser/_parser.py
  nepali/datetime/parser/validators.py
  nepali/exceptions.py
  nepali/locations/__init__.py
  nepali/locations/_data.py
  nepali/locations/_locations.py
  nepali/locations/models.py
  nepali/locations/utils.py
  nepali/number.py
  nepali/phone_number.py
  nepali/templatetags/nepalidatetime.py
  nepali/templatetags/nepalinumber.py
  nepali/tests/test_date_converter.py
  nepali/tests/test_datetime.py
  nepali/tests/test_humanize.py
  nepali/tests/test_locations.py
  nepali/tests/test_number.py
  nepali/tests/test_parser.py
  nepali/tests/test_phone_number.py
  nepali/tests/test_timezone.py
  nepali/timezone.py
  nepali/utils.py
  setup.py
Labels: refactor

#28 Merge Readme updates to master
  README.md
  nepali/tests/test_locations.py
Labels: readme

#30 Refactored nepali number
  .pre-commit-config.yaml
  README.md
  nepali/char.py
  nepali/number.py
  nepali/templatetags/nepalinumber.py
  nepali/tests/test_number.py
Labels: refactor

#31 Feature: Add skeleton for class nepalinumber
  nepali/number/__init__.py
  nepali/number/_number.py
  nepali/number/nepalinumber.py
  nepali/number/utils.py
Labels: enhancement

#32 Refactoring, Coding Standard, and Fomatting done
  .gitignore
  .pre-commit-config.yaml
  CHANGELOG.md
  CONTRIBUTION.md
  Makefile
  README.md
  nepali/date_converter.py
  nepali/datetime/_datetime.py
  nepali/datetime/_humanize.py
  nepali/datetime/parser/_parser.py
  nepali/datetime/parser/validators.py
  nepali/datetime/utils.py
  nepali/number.py
  nepali/phone_number.py
  nepali/templatetags/nepalidatetime.py
  nepali/tests/test_datetime.py
  nepali/tests/test_timezone.py
  nepali/timezone.py
  nepali/utils.py
  requirements.txt
  setup.py
Labels: refactor, unittest
